# Generated by Django 5.1.4 on 2024-12-31 18:02

import Ecomapp.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='path/to/upload')),
                ('name', models.CharField(max_length=150)),
                ('MRP', models.FloatField(max_length=150, null=True)),
                ('SP', models.FloatField(max_length=150, null=True)),
                ('status', models.BooleanField(default=False, help_text='Whether the category is hidden or not')),
                ('trending', models.BooleanField(default=False, help_text='Whether the category is trending or not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='uploads/blog_images/')),
                ('heading', models.CharField(max_length=150)),
                ('description', models.TextField(max_length=1800)),
            ],
        ),
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Ecomapp.models.get_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Ecomapp.models.get_file_path)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False, help_text='Whether the category is hidden or not')),
                ('trending', models.BooleanField(default=False, help_text='Whether the category is trending or not')),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.TextField()),
                ('meta_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='path/to/upload')),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False, help_text='Whether the category is hidden or not')),
                ('trending', models.BooleanField(default=False, help_text='Whether the category is trending or not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name3', models.CharField(max_length=200)),
                ('Email3', models.EmailField(max_length=254)),
                ('Phone3', models.CharField(max_length=200)),
                ('Product3', models.CharField(max_length=200)),
                ('Model3', models.CharField(max_length=200)),
                ('Uploadbill3', models.ImageField(blank=True, null=True, upload_to=Ecomapp.models.get_file_path)),
                ('Message3', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=200)),
                ('Message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Delership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='path/to/upload')),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('image', models.ImageField(blank=True, null=True, upload_to='path/to/upload')),
                ('name', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False, help_text='Whether the category is hidden or not')),
                ('MRP', models.FloatField(null=True)),
                ('SP', models.FloatField(blank=True, null=True)),
                ('trending', models.BooleanField(default=False, help_text='Whether the category is trending or not')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name2', models.CharField(max_length=200)),
                ('Email2', models.EmailField(max_length=254)),
                ('Phone2', models.CharField(max_length=200)),
                ('Product2', models.CharField(max_length=200)),
                ('Message2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to=Ecomapp.models.get_file_path)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('Description', models.CharField(blank=True, max_length=1200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=10)),
                ('Total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Status', models.CharField(default='Pending', max_length=50)),
                ('tracking_no', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateField(auto_now_add=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Ecomapp.models.get_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_file', models.FileField(upload_to=Ecomapp.models.get_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Newproducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('Product_image', models.ImageField(blank=True, null=True, upload_to=Ecomapp.models.get_file_path)),
                ('Small_description', models.TextField(max_length=250)),
                ('Quantity', models.IntegerField()),
                ('description', models.TextField(max_length=500)),
                ('Orignal_Price', models.FloatField()),
                ('Selling_Price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='Whether the category is hidden or not')),
                ('trending', models.BooleanField(default=False, help_text='Whether the category is trending or not')),
                ('Tag', models.CharField(max_length=150)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.TextField()),
                ('meta_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecomapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=100)),
                ('Lname', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.CharField(max_length=15)),
                ('Address', models.TextField()),
                ('City', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('Pincode', models.CharField(max_length=10)),
                ('Payment_mode', models.CharField(max_length=20)),
                ('Payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('Total_price', models.FloatField()),
                ('tracking_no', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orderhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.ManyToManyField(to='Ecomapp.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('Product_image', models.ImageField(blank=True, null=True, upload_to=Ecomapp.models.get_file_path)),
                ('Small_description', models.TextField(max_length=250)),
                ('Size', models.TextField(max_length=150, null=True)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('description2', models.TextField(max_length=1000, null=True)),
                ('Orignal_Price', models.FloatField()),
                ('Selling_Price', models.FloatField()),
                ('status', models.BooleanField(default=False, help_text='Whether the category is hidden or not')),
                ('trending', models.BooleanField(default=False, help_text='Whether the category is trending or not')),
                ('Tag', models.CharField(max_length=150)),
                ('meta_title', models.CharField(max_length=150)),
                ('meta_keywords', models.TextField()),
                ('meta_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecomapp.category')),
            ],
        ),
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField(default=False)),
                ('Quantity', models.IntegerField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecomapp.order')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecomapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecomapp.product'),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='Ecomapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='subCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='path/to/upload')),
                ('small_description', models.TextField(max_length=250, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('original_price', models.FloatField(null=True)),
                ('selling_price', models.FloatField(null=True)),
                ('status', models.BooleanField(default=False, help_text='Whether the category is hidden or not')),
                ('trending', models.BooleanField(default=False, help_text='Whether the category is trending or not')),
                ('tag', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Ecomapp.category1')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Ecomapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
